---

# mysql installation

- name: install mysql 
  action: apt pkg=$item state=installed
  with_items:
   - mysql-server
   - mysql-client
   - python-mysqldb
  tags: mysql

- name: copy mysql configuration file
  copy: src=etc/mysql/my.cnf
        dest=/etc/mysql/my.cnf
  tags: mysql

- include: mysql-secure.yml