---

# mysql installation
- name: install mysql 
  apt: pkg={{item}} state=installed update_cache=yes
  with_items:
   - mysql-server
   - mysql-client
   - python-mysqldb
  tags: mysql

- name: copy mysql configuration file
  copy: src=etc/mysql/my.cnf
        dest=/etc/mysql/my.cnf
  notify:
   - restart mysql
  tags: mysql

- include: mysql-secure.yml