---
- name: update mysql root password for all root accounts
  mysql_user: login_unix_socket=/var/run/mysqld/mysqld.sock name=root host={{ item }} password={{ mysql_root_password }} priv=*.*:ALL,GRANT 
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: MySQL | Config for easy access as root user
  template: src=dot-my-cnf.j2 dest=~/.my.cnf
  tags: mysql

- name: MySQL | Delete anonymous MySQL server user for 
  mysql_user: login_unix_socket=/var/run/mysqld/mysqld.sock user="" host="{{ ansible_hostname }}" state="absent"
  tags: mysql

- name: MySQL | Delete anonymous MySQL server user for localhost
  mysql_user: login_unix_socket=/var/run/mysqld/mysqld.sock user="" state="absent"
  tags: mysql

- name: MySQL | Remove the MySQL test database
  mysql_db: login_unix_socket=/var/run/mysqld/mysqld.sock db=test state=absent
  tags: mysql